#!/usr/bin/env bash
# Bash script that configuresnew Ubuntu machine to respect above requirement

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
